#!/bin/bash
python setup.py clean
python setup.py develop
unset -f ns
unset -f pod

eval "$(_NS_COMPLETE=source_bash ns)"
eval "$(_POD_COMPLETE=source_bash pod)"
eval "$(_LOG_COMPLETE=source_bash log)"
eval "$(_MG_COMPLETE=source_bash mg)"

function ns() { cd $(~/code/mgshell/v/bin/ns $1); }
function pod() { cd $(~/code/mgshell/v/bin/pod $1); }
